version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    groups:
      java-test-dependencies:
        patterns:
          - "org.junit.jupiter:*"
      maven-build-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.sonatype.plugins:*"
          - "com.github.hypfvieh:*"
      java-production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "org.openjfx:*"
          - "org.apache.maven.plugins:*"
          - "org.junit.jupiter:*"
          - "org.sonatype.plugins:*"
          - "com.github.hypfvieh:*"

  - package-ecosystem: "github-actions"
    directory: "/" # even for `.github/workflows`
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "misc:ci"
