language: java
# Testing D-Bus on Travis CI requires an UI, which is
# available, but a new wallet in particular can _not_
# be created via a CLI
# services:
#   - xvfb
sudo: true
jdk:
  - openjdk14
  - oraclejdk14
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
env: []
addons: {}
#before_install:
# - sudo apt-get update
# - sudo apt-get install -y dbus dbus-java-bin dbus-x11
# - sudo apt-get install -y kwalletmanager
# - export $(dbus-launch)
install: skip
script:
  - mvn compile
#  - mvn clean test verify -P coverage
after_success: skip
before_deploy: skip
deploy: []
tags: true